# Generated by Django 5.1.6 on 2025-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField()),
                ('type', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('suites', models.IntegerField()),
                ('parkingSpaces', models.IntegerField()),
                ('amenities', models.JSONField(default=list)),
                ('installations', models.JSONField(default=list)),
                ('salePrice', models.FloatField()),
                ('iptuPlusCondominium', models.FloatField()),
                ('url_coverImage', models.CharField(max_length=255)),
                ('url_orderedImageList', models.JSONField(default=list)),
                ('direct_url', models.URLField()),
                ('forRent', models.BooleanField(default=False)),
                ('forSale', models.BooleanField(default=False)),
                ('rent_price', models.FloatField(blank=True, null=True)),
                ('total_cost_rent', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('neighbourhood', models.CharField(max_length=255)),
                ('regionName', models.CharField(max_length=255)),
            ],
        ),
    ]
