# Generated by Django 5.1.6 on 2025-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
