# Generated by Django 5.1.6 on 2025-02-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='direct_url',
            field=models.CharField(max_length=255),
        ),
    ]
