# Generated by Django 5.1.6 on 2025-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_property_direct_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='uu_id',
            field=models.CharField(max_length=255),
        ),
    ]
