# Generated by Django 5.1.6 on 2025-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_property_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='direct_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='iptuPlusCondominium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parkingSpaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='regionName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='salePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='suites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_cost_rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='url_coverImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='url_orderedImageList',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
