# Generated by Django 5.1.6 on 2025-02-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_property_address_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='iptuPlusCondominium',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='salePrice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_cost_rent',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
