# Generated by Django 5.1.6 on 2025-02-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_property_iptupluscondominium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='installations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
