# Generated by Django 5.1.6 on 2025-02-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_property_amenities_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
