# Generated by Django 5.1.6 on 2025-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.AlterField(
            model_name='property',
            name='forRent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='forSale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
